GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "title": "John Doe",
    "foto": "https.blablablablablablabla",
    "berita": "waw gokil"
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "title": "M Fikri",
    "foto": "mfikri@gmail.com",
    "berita": "Male"
}

###
DELETE http://localhost:5000/users/2